import javax.*;
import javax.servlet.*;
import java.io.*;
import javax.servlet.http.*;

public class Servlet extends HttpServlet {
public void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException
{
PrintWriter out;
try {

out= res.getWriter();
out.print("<html><head><title> Response From Servlet </title></head>");
out.print("<body><p><h3> This Text Is Generated By Invoked Servlet </h3></body></html>");
} catch(Exception ie)
{
System.out.println(ie);
} } }